---
- name: "Initialize role | {{ _title_pfx }}"
  become: true
  tags: always
  block:
    - name: "Display title | Init | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg:
          - "######################################################################################"
          - "##                              HASHICORP VAULT SERVER                              ##"
          - "######################################################################################"

    - name: "Header | Init | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "---------------------------------- INIT ----------------------------------"

    - name: "Ensure tmp directory exists | Init | {{ _title_pfx }}"
      ansible.builtin.file:
        path: "{{ hashivault__tmp_dir }}"
        state: directory
        mode: "0755"

    - name: "Check required parameters | Init | {{ _title_pfx }}"
      ansible.builtin.assert:
        that:
          - "{{ item }} | default('', true) | length > 0"
        fail_msg: "Required parameter '{{ item }}' is not defined."
        success_msg: "Required parameter '{{ item }}' is ok."
        quiet: true
      loop:
        - hashivault__version
        - hashivault__server_fqdn
