---
- name: "Install Hashicorp Vault server | Install | Install Selfsigned certificate | {{ _title_pfx }}"
  become: true
  tags: selfsigned
  block:
    - name: "Generate an OpenSSL private key | Install | Install Selfsigned certificate | {{ _title_pfx }}"
      community.crypto.openssl_privatekey:
        path: "{{ hashivault__config_dir }}/tls/selfsigned-key.pem"
        size: "{{ hashivault__tls_size }}"
        type: "{{ hashivault__tls_type }}"
        mode: "0640"
        owner: root
        group: "{{ hashivault__group }}"
        state: present
      when: hashivault__tls_provider == 'selfsigned'

    - name: "Create certificate signing request (CSR) for self-signed certificate | Install | Install Selfsigned certificate | {{ _title_pfx }}"
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ hashivault__config_dir }}/tls/selfsigned-key.pem"
        common_name: "{{ hashivault__server_fqdn }}"
        organization_name: "{{ hashivault__tls_selfsigned_csr_organization }}"
        country_name: "{{ hashivault__tls_selfsigned_csr_country }}"
        state_or_province_name: "{{ hashivault__tls_selfsigned_csr_state }}"
        locality_name: "{{ hashivault__tls_selfsigned_csr_locality }}"
        organizational_unit_name: "{{ hashivault__tls_selfsigned_csr_ou }}"
        subject_alt_name: "{{ hashivault__tls_selfsigned_csr_sans }}"
      register: _csr
      when: hashivault__tls_provider == 'selfsigned'

    - name: "Create self-signed certificate from (CSR) | Install | Install Selfsigned certificate | {{ _title_pfx }}"
      community.crypto.x509_certificate:
        path: "{{ hashivault__config_dir }}/tls/selfsigned-cert.pem"
        csr_content: "{{ _csr.csr }}"
        privatekey_path: "{{ hashivault__config_dir }}/tls/selfsigned-key.pem"
        provider: selfsigned
        mode: "0644"
        owner: root
        group: root
        state: present
      when: hashivault__tls_provider == 'selfsigned'
