---
- name: "Post-install Hashicorp Vault server | Post_install | {{ _title_pfx }}"
  become: true
  tags: post_install
  environment:
    VAULT_ADDR: "https://{{ hashivault__server_fqdn }}:8200"
    VAULT_SKIP_VERIFY: "{{ (hashivault__tls_provider != 'selfsigned') | ternary('false', 'true') }}"
  block:
    - name: "Header | Post_install | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "------------------------------------ POST_INSTALL ------------------------------------"

    - name: "Read root token from files | Post_install | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: "cat /root/.vault-token"
      register: _root_token
      changed_when: _root_token.rc == 0
      no_log: "{{ not hashivault__debugger }}"

    - name: "Login to Hashicorp Vault server | Post_install | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: "vault login {{ _root_token.stdout }}"
      register: _login
      changed_when: _login.rc == 0
      run_once: true
      no_log: "{{ not hashivault__debugger }}"

    - name: "Check Hashicorp Vault server audit enabled | Post_install | {{ _title_pfx }}"
      ansible.builtin.shell:
        cmd: "set -o pipefail && vault audit list | grep -c file"
        executable: /bin/bash
      register: _audit_list
      changed_when: _audit_list.rc == 0
      failed_when: _audit_list.rc not in [0, 1]

    - name: "Enable Hashicorp Vault server audit device | Post_install | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: "vault audit enable -local file file_path={{ hashivault__install_dir }}/log/vault_audit.log"
      register: _audit_enable
      when: _audit_list.stdout == "0"
      changed_when: _audit_enable.rc == 0
      failed_when: _audit_enable.rc != 0
      run_once: true

    - name: "Check Hashicorp Vault KV secret engine enabled | Post_install | {{ _title_pfx }}"
      ansible.builtin.shell:
        cmd: "set -o pipefail && vault secrets list | grep -c {{ hashivault__kv_secret_engine_path }}"
        executable: /bin/bash
      register: _kv_list
      changed_when: _kv_list.rc == 0
      failed_when: _kv_list.rc not in [0, 1]

    - name: "Enable Hashicorp Vault KV secret engine | Post_install | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: "vault secrets enable -path={{ hashivault__kv_secret_engine_path }} kv-v2"
      register: _kv_enable
      when: _kv_list.stdout == "0"
      changed_when: _kv_enable.rc == 0
      failed_when: _kv_enable.rc != 0
      run_once: true

    - name: "Check Hashicorp Vault Approle auth enabled | Post_install | {{ _title_pfx }}"
      ansible.builtin.shell:
        cmd: "set -o pipefail && vault auth list | grep -c approle"
        executable: /bin/bash
      register: _approle_list
      changed_when: _approle_list.rc == 0
      failed_when: _approle_list.rc not in [0, 1]

    - name: "Enaable Hashicorp Vault Approle auth method | Post_install | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: "vault auth enable approle"
      register: _approle_enable
      when: _approle_list.stdout == "0"
      changed_when: _approle_enable.rc == 0
      failed_when: _approle_enable.rc != 0
      run_once: true

    - name: "Safe root token | Post_install | {{ _title_pfx }}"
      ansible.builtin.fetch:
        src: "/root/.vault-token"
        dest: "root_hv_token.txt"
        flat: true
