---
- name: "Uninstall Hashicorp Vault server | Uninstall | {{ _title_pfx }}"
  become: true
  tags: [never, uninstall]
  block:
    - name: "Header | Uninstall | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "--------------------------------------- UNINSTALL ---------------------------------------"

    - name: "Stop Hashicorp Vault service | Uninstall | {{ _title_pfx }}"
      ansible.builtin.systemd_service:
        name: vault
        state: stopped
        enabled: false

    - name: "Uninstall Hashicorp Vault service | Uninstall | {{ _title_pfx }}"
      ansible.builtin.file:
        path: /etc/systemd/system/vault.service
        state: absent

    - name: "Uninstall Hashicorp Vault directories | Uninstall | {{ _title_pfx }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ hashivault__config_dir }}"
        - "{{ hashivault__install_dir }}"

    - name: "Unset Hashicorp Vault path env | Uninstall | {{ _title_pfx }}"
      ansible.builtin.file:
        path: /etc/profile.d/hashivault.sh
        state: absent

    - name: "Delete Hashicorp Vault user | Uninstall | {{ _title_pfx }}"
      ansible.builtin.user:
        name: "{{ hashivault__user }}"
        state: absent

    - name: "Delete Hashicorp Vault group | Uninstall | {{ _title_pfx }}"
      ansible.builtin.group:
        name: "{{ hashivault__group }}"
        state: absent

    - name: "Enable swap | Uninstall | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: swapon -a
      register: _cmd_result
      changed_when: _cmd_result.rc == 0
      when: ansible_virtualization_type != "lxc"

    - name: "Restore swap partition | Uninstall | {{ _title_pfx }}"
      ansible.builtin.command:
        cmd: mv /etc/fstab.* /etc/fstab
      register: _cmd_result2
      changed_when: _cmd_result2.rc == 0
      when: ansible_virtualization_type != "lxc"
